# frozen_string_literal: true

# LeetCode 389: Find the Difference
#
# Problem:
# You are given two strings s and t where t is generated by shuffling s and
# adding one more random lowercase letter. Return the letter added to t.
#
# -----------------------------------------------------------------------------
# Interview Flow
#
# 1. True Brute Force
#    Count characters in s and t; find the one with one extra in t.
#    Time Complexity: O(n)
#    Space Complexity: O(1) — 26 chars max
#
# 2. Bottleneck
#    Hash map approach is already O(n) and simple.
#
# 3. Optimized Accepted Approach
#    XOR all characters in s and t. Pairs cancel; extra character remains.
#    Time Complexity: O(n)
#    Space Complexity: O(1)
#
# -----------------------------------------------------------------------------
# Dry Run
#
# s = "abcd", t = "abcde"
# XOR all chars: a^b^c^d ^ a^b^c^d^e = e ✓
# (each char in s appears twice, XOR cancels; 'e' appears once)
#
# Edge Cases:
# - s is empty → return t[0]
# - Extra char is 'a' → still works with XOR

def find_the_difference_brute(s, t)
  freq = Hash.new(0)
  s.each_char { |c| freq[c] += 1 }
  t.each_char { |c| freq[c] -= 1 }
  freq.find { |_, count| count != 0 }[0]
end

def find_the_difference(s, t)
  result = 0
  s.each_char { |c| result ^= c.ord }   # XOR all chars in s
  t.each_char { |c| result ^= c.ord }   # XOR all chars in t; pairs cancel
  result.chr                             # remaining is the extra char
end

if __FILE__ == $PROGRAM_NAME
  puts "Brute: #{find_the_difference_brute("abcd", "abcde")}"  # "e"
  puts "Opt:   #{find_the_difference("abcd", "abcde")}"        # "e"
  puts "Brute: #{find_the_difference_brute("", "y")}"          # "y"
  puts "Opt:   #{find_the_difference("", "y")}"                # "y"
end
